prometheus:
  replicaCount: 1
  image:
    repository: prom/prometheus
    tag: v2.0.0
    pullPolicy: Always
  args:
    - '--config.file=/etc/prometheus/prometheus.yml'
    - '--storage.tsdb.path=/data'
    - '--web.external-url=https://prometheus.domain.com'
    - '--web.listen-address=0.0.0.0:9090'
  service:
    name: prometheus
    type: ClusterIP
    externalHttpPort: 9090
    internalHttpPort: 9090
  ingress:
    enabled: false
    hosts:
      - prometheus.domain.com
    annotations:
      kubernetes.io/ingress.class: nginx
  resources:
    limits:
      cpu: 200m
      memory: 1024Mi
    requests:
      cpu: 200m
      memory: 1024Mi
  volumes:
    configMap:
      config:
        name: config-volume
        mountPath: /etc/prometheus
      rules:
        name: prometheus-rules
        mountPath: /etc/prometheus-rules
    pv:
      data:
        name: prometheus-data
        claimName: prometheus-pvc
        mountPath: /data
