{{- if .Values.prometheus.ingress.enabled -}}
{{- $serviceName := .Values.prometheus.service.name -}}
{{- $servicePort := .Values.prometheus.service.externalHttpPort -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations:
    {{- range $key, $value := .Values.prometheus.ingress.annotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  rules:
    {{- range $host := .Values.prometheus.ingress.hosts }}
    - host: {{ $host }}
      http:
        paths:
          - path: /
            backend:
              serviceName: "monitor-{{ $serviceName }}"
              servicePort: {{ $servicePort }}
    {{- end -}}
  {{- if .Values.prometheus.ingress.tls }}
  tls:
{{ toYaml .Values.prometheus.ingress.tls | indent 4 }}
  {{- end -}}
{{- end -}}
