kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: "{{ template "fullname" . }}-ssd"
  annotations:
    storageclass.beta.kubernetes.io/is-default-class: "false"
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
